# theme: jekyll-theme-minimal

# Site settings                    
title: Secret Garden                            # title
SEOTitle: 白金燐子の活動記録                        # subtitle
# header-img: 
email: mahiru.hikawa@gmail.com
url: https://aslla-piscu.github.io/asllapiscu.github.io/
#description:                                     # side common

# SNS settings
github_username: aslla-piscu
instagram_username: ssj_horus

# Build settings
# paginate: 7

# Sidebar settings
sidebar: true  #添加侧边栏
sidebar-about-description: ""
sidebar-avatar: https://github.com/aslla-piscu/asllapiscu.github.io/blob/master/img/71397833_p0.png    #你的大头贴，请使用绝对地址.注意：名字区分大小写！后缀名也是

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
